theme:      tale

# Site settings
title:          intelyShoen
description:    "Web Designer, Publisher, Dev"
url:            "https://intelyshoen.github.io"

# Author
author:
  name:         intelyshoen
  url:          https://intelyshoen.github.io
  email:        intelyhsoen@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

